EinsteinDiffusionNode:
  correlation_time: 1
  data_range: 100
NPT:
  parameters:
    barostat_factor: 500
    dump_interval: 1000
    input_nstep: 0
    name: NPT
    pressure: 1.0
    steps: 200000
    temperature: 1250
    thermo_intervall: 1000
    timestep: 0.001
NVT:
  parameters:
    barostat_factor: 500
    dump_interval: 1000
    input_nstep: 0
    name: NVT
    pressure: 1.0
    steps: 200000
    temperature: 1250
    thermo_intervall: 1000
    timestep: 0.001
